"use client";
import {useParams,useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import AppShell,{Loading} from "@/components/AppShell";
import {apiRequest} from "@/lib/api";
export default function TestPage(){
 const {testId}=useParams();const router=useRouter();const [test,setTest]=useState(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{apiRequest(`/tests/${testId}`).then(async r=>{let t=r.data?.test;if(t?.status==="generated"){const started=await apiRequest(`/tests/${testId}/start`,{method:"POST"});t=started.data?.test}setTest(t)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[testId]);
 const q=test?.questions?.[index];const setAnswer=v=>setAnswers({...answers,[q.id]:v});
 const submit=async()=>{if(!confirm("Submit your answers? You cannot change them later."))return;setBusy(true);setError("");try{await apiRequest(`/tests/${testId}/submit`,{method:"POST",body:JSON.stringify({answers:Object.entries(answers).map(([questionId,answer])=>({questionId,answer}))})});router.push(`/result/${testId}`);}catch(e){setError(e.message);setBusy(false);}};
 return <AppShell>{loading?<Loading label="Preparing your assessment..."/>:<div className="question-shell"><div className="page-head"><div><div className="eyebrow">AI assessment · Attempt {test?.attemptNumber}</div><h1>Show what you learned</h1><p>{test?.totalQuestions} questions generated from your lesson.</p></div><div className="badge badge-warning">{Object.keys(answers).length}/{test?.totalQuestions} answered</div></div>{error&&<div className="form-error">{error}</div>}{q&&<div className="card"><div className="question-top"><span>Question {index+1} of {test.questions.length}</span><span>{q.difficulty} · {q.type.replace("_"," ")}</span></div><div className="progress-track" style={{marginBottom:25}}><span style={{width:`${((index+1)/test.questions.length)*100}%`}}/></div><h2 style={{fontSize:23,lineHeight:1.45}}>{q.question}</h2>{q.options?.length?q.options.map(o=><label className={`option test-answer-option ${answers[q.id]===o?"selected":""}`} key={o}><input type="radio" checked={answers[q.id]===o} onChange={()=>setAnswer(o)}/><span>{o}</span></label>):<textarea className="textarea" placeholder="Write your answer in your own words..." value={answers[q.id]||""} onChange={e=>setAnswer(e.target.value)}/>}<div className="question-nav"><button className="btn btn-outline" disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button>{index<test.questions.length-1?<button className="btn btn-primary" onClick={()=>setIndex(index+1)}>Next →</button>:<button className="btn btn-primary" disabled={busy} onClick={submit}>{busy?"Grading...":"Submit test"}</button>}</div></div>}</div>}</AppShell>
}
